spring:
  datasource:
    url: jdbc:postgresql://db-bilem-do-user-14309045-0.b.db.ondigitalocean.com:25060/bilemDB
    username: doadmin
    password: AVNS_q1bzRfY_q3Kg6TbFdQ9
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: teamtwo.summer@gmail.com
    password: zzriwjhdygyhxbym
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
app:
  jwtSecret: 397A24432646294A404E635266546A576E5A7234753778214125442A472D4B61
  jwtExpirationInMs: 3600000
  refreshExpirationInMs: 259200000
  recoveryValidityInSeconds: 7200
server:
  port: 8080
